name: 'CHD Portal Custom Test Action'
description: 'Run tests for updated services and comment the coverage'
inputs:
  token:
    description: >
      GitHub token for GitHub API requests.
      No need to set this unless need to use a different token.
    required: true
    default: ${{ github.token }}
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'file-text'
  color: 'purple'
